import type { ICategoriesResponse } from '../categories/categories-response';
// Generated by https://quicktype.io

export interface ISalesResponse {
    sales: ISale[];
}

export interface ISale {
    id:        number;
    client:    string;
    total:     number;
    products:  IProductSale[];
    createdAt: string;
}

export interface IProductSale {
    name:        string;
    description: string;
    slug:        string;
    price:       number;
    image:       string;
    category:    ICategoriesResponse;
    createdAt:   string;
    quantity:    number;
}