// Generated by https://quicktype.io

import type { ICategoriesResponse } from "..";

export interface IFullProduct {
    product: IProduct;
}

export interface IProduct {
    id:          number;
    name:        string;
    description: string;
    stock:       number;
    slug:        string;
    price:       number;
    image:       string;
    category:    ICategoriesResponse;
    createdAt:   string;
}
